# Generated by Django 4.0.6 on 2022-08-18 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='next_visit_date',
            field=models.DateTimeField(),
        ),
    ]
